# Generated by Django 5.2.6 on 2025-09-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Не начато', 'Не начато'), ('В процессе', 'В процессе'), ('Завершенно', 'Завершено')], max_length=30),
        ),
    ]
